# https://jupyterbook.org/en/stable/customize/config.html
name: quanttide-handbook-of-public-relations
title: 量潮公共关系手册
author: 量潮科技
description: 量潮公共关系手册
# Jupyter Book Config
only_build_toc_files: true